version: '3'

volumes:
  postgres_data:
      driver: local

services:
  service-discovery:
    build: ./service-discovery
    ports:
      - 8761:8761

  config-server:
    build: ./config-server
    ports:
      - 8888:8888
    depends_on:
      - service-discovery
  
  gateway:
    build: ./gateway
    ports:
      - 8080:8080
    depends_on:
      - config-server
      - keycloak
      - files-uploader
      - tours-locations-layers
      - users-manager
  
  users-manager:
    build: ./users-manager
    ports:
      - 8084:8084
    depends_on:
      - config-server
      - keycloak

  files-uploader:
    build: ./files-uploader
    ports:
      - 8087:8087
    depends_on:
      - config-server
      - database
  
  tours-locations-layers:
    build: ./tours-locations-layers
    ports:
      - 8090:8090
    depends_on:
      - config-server
      - database
      - keycloak
  
  tours-ui:
    build: ./tours-ui
    ports:
      - 80:80
    depends_on:
      - gateway

  database:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: tours

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./keycloak/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8180:8080
    depends_on:
      - postgres