spring:
  application:
    name: eureka-discovery-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

server:
  port: 8761

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
