spring:
  application:
    name: tours-locations-layers
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/tours
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
