spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/tours
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://database:3306/tours
    username: root
    password: password
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-discovery-service:8761/eureka