spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${WEBSITE_HOST:localhost}:8180/auth/realms/my_realm
          jwk-set-uri: http://${WEBSITE_HOST:localhost}:8180/auth/realms/my_realm/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        event:
          merge:
            entity_copy_observer: allow
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/tours
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  zipkin:
    baseUrl: http://${ZIPKIN_HOST:localhost}:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://database:3306/tours
    username: root
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/auth/realms/my_realm/protocol/openid-connect/certs
  zipkin:
    baseUrl: http://zipkin:9411/
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-discovery-service:8761/eureka
