spring:
  zipkin:
    baseUrl: http://${ZIPKIN_HOST:localhost}:9411/
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://zipkin:9411/
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-discovery-service:8761/eureka