spring:
  application:
    name: files-uploader
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8087
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka